# Generated by Django 4.1.6 on 2023-02-10 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='submittedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 18, 44, 3, 522365)),
        ),
    ]
