# Generated by Django 4.1.6 on 2023-02-10 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_team_submittedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shortName',
            field=models.CharField(default='shortName', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='submittedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 19, 0, 15, 873021)),
        ),
    ]
